<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260402180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Waitlist, reservation extension_count, activity_log';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id INT DEFAULT NULL, details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F647A76ED395 ON activity_log (user_id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE book_waitlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_id INT NOT NULL, member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BOOK_WAITLIST_MEMBER_BOOK ON book_waitlist (member_id, book_id)');
        $this->addSql('CREATE INDEX IDX_9F74A28F16A2B381 ON book_waitlist (book_id)');
        $this->addSql('CREATE INDEX IDX_9F74A28F7597D3FE ON book_waitlist (member_id)');
        $this->addSql('ALTER TABLE book_waitlist ADD CONSTRAINT FK_9F74A28F16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE book_waitlist ADD CONSTRAINT FK_9F74A28F7597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE reservation ADD extension_count INT DEFAULT 0 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE reservation DROP extension_count');
        $this->addSql('ALTER TABLE book_waitlist DROP CONSTRAINT FK_9F74A28F7597D3FE');
        $this->addSql('ALTER TABLE book_waitlist DROP CONSTRAINT FK_9F74A28F16A2B381');
        $this->addSql('DROP TABLE book_waitlist');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647A76ED395');
        $this->addSql('DROP TABLE activity_log');
    }
}
