<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Bibliothèques (lieux de retrait), liaison livre → bibliothèque, réservation → usager.
 */
final class Version20260402150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Library branch, book.library_id, reservation.member_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE library (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(120) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('INSERT INTO library (name, address, city) VALUES (\'Bibliothèque municipale — Centre\', \'12 rue des Livres\', \'Paris\')');
        $this->addSql('INSERT INTO library (name, address, city) VALUES (\'Bibliothèque de quartier — Nord\', \'45 avenue des Érables\', \'Paris\')');
        $this->addSql('INSERT INTO library (name, address, city) VALUES (\'Médiathèque intercommunale\', \'8 place de la Lecture\', \'Lyon\')');

        $this->addSql('ALTER TABLE book ADD library_id INT DEFAULT NULL');
        $this->addSql('UPDATE book SET library_id = (SELECT id FROM library ORDER BY id ASC LIMIT 1) WHERE library_id IS NULL');
        $this->addSql('ALTER TABLE book ALTER COLUMN library_id SET NOT NULL');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_book_library FOREIGN KEY (library_id) REFERENCES library (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_CBE5A331537732B0 ON book (library_id)');

        $this->addSql('DELETE FROM reservation');
        $this->addSql('ALTER TABLE reservation ADD member_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation ALTER COLUMN book_id SET NOT NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A76ED395 FOREIGN KEY (member_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_42C84955A76ED395 ON reservation (member_id)');
        $this->addSql('ALTER TABLE reservation ALTER COLUMN member_id SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955A76ED395');
        $this->addSql('DROP INDEX IDX_42C84955A76ED395');
        $this->addSql('ALTER TABLE reservation DROP COLUMN member_id');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_book_library');
        $this->addSql('DROP INDEX IDX_CBE5A331537732B0');
        $this->addSql('ALTER TABLE book DROP COLUMN library_id');
        $this->addSql('DROP TABLE library');
    }
}
