<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402134629 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        // reservation is created in Version20260402134139
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT DEFAULT NULL, book_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68C58ED97597D3FE ON favorite (member_id)');
        $this->addSql('CREATE INDEX IDX_68C58ED916A2B381 ON favorite (book_id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED97597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED916A2B381 FOREIGN KEY (book_id) REFERENCES book (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED97597D3FE');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED916A2B381');
        $this->addSql('DROP TABLE favorite');
    }
}
